apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
#    targetPort: {{ .Values.service.internalPort }}
#    name: {{ .Values.service.name }}
  selector:
    app: {{.Release.Name}}
